# Generated by Django 6.0.5 on 2026-05-23 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=20)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married')], max_length=20, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('alternate_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(default='Pakistan', max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('cnic_number', models.CharField(max_length=20, unique=True)),
                ('cnic_front', models.ImageField(upload_to='customer_profile/cnic/')),
                ('cnic_back', models.ImageField(upload_to='customer_profile/cnic/')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='customer_profile/profile/')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('relation', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('interested_packages', models.CharField(blank=True, max_length=255, null=True)),
                ('budget_preference', models.CharField(blank=True, choices=[('economy', 'Economy'), ('standard', 'Standard'), ('premium', 'Premium'), ('luxury', 'Luxury')], max_length=20, null=True)),
                ('travel_type', models.CharField(blank=True, choices=[('solo', 'Solo'), ('family', 'Family'), ('group', 'Group')], max_length=20, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=10, null=True)),
                ('wheelchair_required', models.BooleanField(default=False)),
                ('medical_condition', models.TextField(blank=True, null=True)),
                ('is_profile_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
