# Generated by Django 6.0.5 on 2026-09-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customerprofile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='cnic_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
