# Generated by Django 6.0.5 on 2026-06-19 04:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_alter_package_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='agency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='package',
            name='banner',
            field=models.ImageField(default='package_banners/default.jpg', upload_to='package_banners/'),
        ),
        migrations.AddField(
            model_name='package',
            name='departure_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='package',
            name='madinah_hotel',
            field=models.CharField(default='Standard Hotel', max_length=255),
        ),
        migrations.AddField(
            model_name='package',
            name='makkah_hotel',
            field=models.CharField(default='Standard Hotel', max_length=255),
        ),
        migrations.AddField(
            model_name='package',
            name='ticket',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='transport',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='visa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='ziyarat',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='package',
            name='application_deadline',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='package',
            name='city',
            field=models.CharField(default='Makkah', max_length=100),
        ),
        migrations.AlterField(
            model_name='package',
            name='country',
            field=models.CharField(default='Saudi Arabia', max_length=100),
        ),
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.TextField(default='Package details coming soon...'),
        ),
        migrations.AlterField(
            model_name='package',
            name='duration_days',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=10, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(2500000)]),
        ),
        migrations.AlterField(
            model_name='package',
            name='tier',
            field=models.CharField(choices=[('economy', 'Economy'), ('standard', 'Standard'), ('vip', 'VIP'), ('luxury', 'Luxury')], default='standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='package',
            name='total_seats',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
