# Generated by Django 6.0.5 on 2026-07-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_package_agency_package_banner_package_departure_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagetype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='package_types/'),
        ),
    ]
