# Generated by Django 6.0.5 on 2026-09-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_packagetype_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='meals',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='package',
            name='city',
            field=models.CharField(blank=True, default='Makkah', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='madinah_hotel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='makkah_hotel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('draft', 'Draft'), ('closed', 'Closed'), ('blocked', 'Blocked')], default='active', max_length=20),
        ),
    ]
