# Generated by Django 6.0.5 on 2026-09-14 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_package_meals_alter_package_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='package_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='packages.packagetype'),
        ),
    ]
