# Generated by Django 6.0.5 on 2026-09-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0006_alter_package_package_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='airline_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='departure_city',
            field=models.CharField(default='Lahore', max_length=100),
        ),
        migrations.AddField(
            model_name='package',
            name='is_direct_flight',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='package',
            name='madinah_distance_meters',
            field=models.PositiveIntegerField(blank=True, help_text='Distance in meters', null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='makkah_distance_meters',
            field=models.PositiveIntegerField(blank=True, help_text='Distance in meters', null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='sharing_type',
            field=models.CharField(choices=[('sharing', 'Sharing'), ('quad', 'Quad (4 Beds)'), ('triple', 'Triple (3 Beds)'), ('double', 'Double (2 Beds)')], default='quad', max_length=20),
        ),
    ]
