# Generated by Django 6.0.5 on 2026-09-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_commissionsetting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='escrow_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('incomplete', 'Incomplete'), ('failed', 'Failed'), ('payment_submitted', 'Payment Submitted'), ('payment_verified', 'Payment Verified'), ('held_in_escrow', 'Held in Escrow'), ('ticket_uploaded', 'Ticket Uploaded'), ('customer_approved', 'Customer Approved'), ('released', 'Released'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('incomplete', 'Incomplete'), ('failed', 'Failed'), ('payment_submitted', 'Payment Submitted'), ('payment_verified', 'Payment Verified'), ('held_in_escrow', 'Held in Escrow'), ('ticket_uploaded', 'Ticket Uploaded'), ('customer_approved', 'Customer Approved'), ('released', 'Released'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='paymentstatuslog',
            name='new_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('incomplete', 'Incomplete'), ('failed', 'Failed'), ('payment_submitted', 'Payment Submitted'), ('payment_verified', 'Payment Verified'), ('held_in_escrow', 'Held in Escrow'), ('ticket_uploaded', 'Ticket Uploaded'), ('customer_approved', 'Customer Approved'), ('released', 'Released'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], max_length=30),
        ),
        migrations.AlterField(
            model_name='paymentstatuslog',
            name='old_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('incomplete', 'Incomplete'), ('failed', 'Failed'), ('payment_submitted', 'Payment Submitted'), ('payment_verified', 'Payment Verified'), ('held_in_escrow', 'Held in Escrow'), ('ticket_uploaded', 'Ticket Uploaded'), ('customer_approved', 'Customer Approved'), ('released', 'Released'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], max_length=30, null=True),
        ),
    ]
