# Generated by Django 6.0.5 on 2026-05-18 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=255)),
                ('owner_name', models.CharField(max_length=255)),
                ('phone_no', models.CharField(max_length=20)),
                ('whatsapp_no', models.CharField(blank=True, max_length=20)),
                ('office_address', models.TextField()),
                ('is_hajj', models.BooleanField(default=False)),
                ('is_ziyarat', models.BooleanField(default=False)),
                ('ntn_no', models.CharField(max_length=100)),
                ('dts_no', models.CharField(max_length=100)),
                ('cnic_no', models.CharField(max_length=30)),
                ('ntn_doc', models.FileField(upload_to='agent_kyc/ntn/')),
                ('dts_doc', models.FileField(upload_to='agent_kyc/dts/')),
                ('cnic_f', models.FileField(upload_to='agent_kyc/cnic/')),
                ('cnic_b', models.FileField(upload_to='agent_kyc/cnic/')),
                ('munazzam_no', models.CharField(blank=True, max_length=255)),
                ('munazzam_doc', models.FileField(blank=True, null=True, upload_to='agent_kyc/munazzam/')),
                ('iata_type', models.CharField(blank=True, choices=[('own', 'Own IATA'), ('reference', 'Reference IATA')], max_length=20)),
                ('iata_no', models.CharField(blank=True, max_length=255)),
                ('iata_doc', models.FileField(blank=True, null=True, upload_to='agent_kyc/iata/')),
                ('ref_agency_name', models.CharField(blank=True, max_length=255)),
                ('iata_ref_doc', models.FileField(blank=True, null=True, upload_to='agent_kyc/iata_reference/')),
                ('ziy_no', models.CharField(blank=True, max_length=255)),
                ('ziy_doc', models.FileField(blank=True, null=True, upload_to='agent_kyc/ziy/')),
                ('bank_iban', models.CharField(blank=True, max_length=255)),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('easypaisa_no', models.CharField(blank=True, max_length=20)),
                ('easypaisa_name', models.CharField(blank=True, max_length=255)),
                ('jazzcash_no', models.CharField(blank=True, max_length=20)),
                ('jazzcash_name', models.CharField(blank=True, max_length=255)),
                ('kyc_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rollback', 'Rollback'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_comment', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_kyc', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
