# Generated by Django 6.0.5 on 2026-05-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentkyc',
            name='submission_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
