# Generated by Django 6.0.5 on 2026-06-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0002_agentkyc_submission_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentkyc',
            name='rejected_fields',
            field=models.TextField(blank=True, help_text='Comma-separated fields that need to be unlocked'),
        ),
    ]
