# Generated by Django 6.0.5 on 2026-07-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0003_agentkyc_rejected_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentkyc',
            name='bank_iban',
        ),
        migrations.RemoveField(
            model_name='agentkyc',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='agentkyc',
            name='easypaisa_name',
        ),
        migrations.RemoveField(
            model_name='agentkyc',
            name='easypaisa_no',
        ),
        migrations.RemoveField(
            model_name='agentkyc',
            name='jazzcash_name',
        ),
        migrations.RemoveField(
            model_name='agentkyc',
            name='jazzcash_no',
        ),
        migrations.AddField(
            model_name='agentkyc',
            name='raast_id',
            field=models.CharField(blank=True, help_text="Agent's Raast ID (mobile number or IBAN) for escrow payout", max_length=100, null=True),
        ),
    ]
