# Generated by Django 6.0.5 on 2026-06-30 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(choices=[('customer', 'Customer'), ('agent', 'Agent')], max_length=20, verbose_name='Role Type')),
                ('complaint_type', models.CharField(choices=[('no_ticket', 'Flight Ticket Not Received Yet (Customer Issue)'), ('visa_delay', 'Visa Processing Delay / Document Issue'), ('passport_issue', 'Passport Return / Courier Handling Issue'), ('no_payment', 'Payment Pending / Not Received (Agent Issue)'), ('wrong_billing', 'Incorrect Amount Charged / Double Payment'), ('refund_issue', 'Refund Request Pending / Cash Back Delay'), ('transport_missing', 'Transport/Bus Not Arrived at Airport or Hotel'), ('driver_behavior', 'Driver Misbehavior / Route Mismanagement'), ('luggage_lost', 'Luggage Lost / Handling Issue during Transport'), ('hotel_not_booked', 'Hotel Booking Not Found at Check-in (Voucher Issue)'), ('room_quality', 'Room Quality/Amenities Not as Promised (Distance/Food/AC)'), ('ziarat_issue', 'Makkah/Madinah Ziarat Tour Skipped or Delayed'), ('info_not_sent', 'My Information/Data Not Forwarded to Supplier'), ('portal_error', 'Web App Technical Error / System Crash'), ('other', 'Other Operational Issues / Emergency Assistance')], max_length=30, verbose_name='Issue Category')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject Title')),
                ('description', models.TextField(verbose_name='Detailed Grievance')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Filed Date & Time')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('in_progress', 'Under Investigation'), ('resolved', 'Resolved / Closed')], default='pending', max_length=20, verbose_name='Action Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL, verbose_name='Filer / Complainant')),
            ],
            options={
                'verbose_name': 'Customer & Agent Complaint',
                'verbose_name_plural': 'Complaints Control Center',
                'ordering': ['-created_at'],
            },
        ),
    ]
