# Generated by Django 6.0.5 on 2026-08-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_currency', models.CharField(choices=[('PKR', 'PKR'), ('SAR', 'SAR'), ('USD', 'USD')], default='PKR', max_length=10)),
                ('timezone', models.CharField(default='Asia/Karachi', max_length=50)),
                ('maintenance_mode', models.BooleanField(default=False)),
            ],
        ),
    ]
