# Generated by Django 6.0.5 on 2026-08-30 18:51

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_systemsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_slug', models.SlugField(help_text='Page key identifier matching view route', max_length=100, unique=True)),
                ('title', models.CharField(help_text='Page Heading Title', max_length=200)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='guides/banners/')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Guide Content')),
                ('is_published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
