# Generated by Django 6.0.5 on 2026-09-15 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_adminagentchat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adminagentchat',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_admin_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adminagentchat',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_admin_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
