# Generated by Django 6.0.5 on 2026-07-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='customer_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='customer_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='customer_rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
