# Generated by Django 6.0.5 on 2026-08-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_ticket_customer_approved_ticket_customer_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingcustomers',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingcustomers',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('action_required', 'Action Required'), ('visa_processing', 'Visa Processing'), ('ticket_issued', 'Ticket Issued'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('refunded', 'Refunded')], default='pending', max_length=30),
        ),
    ]
