# Generated by Django 6.0.5 on 2026-08-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_bookingdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingcustomers',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('rollback', 'Rollback Requested')], default='pending', max_length=20),
        ),
    ]
