# Generated by Django 6.0.5 on 2026-08-24 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_bookingcustomers_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingcustomers',
            name='field_statuses',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='bookingcustomers',
            name='rollback_remarks',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='bookingcustomers',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profiles', to='bookings.bookings'),
        ),
        migrations.AlterField(
            model_name='bookingcustomers',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resubmitted', 'Resubmitted by User'), ('rollback', 'Rollback Requested')], default='pending', max_length=20),
        ),
    ]
