# Generated by Django 6.0.5 on 2026-09-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_bookingcustomers_field_statuses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingcustomers',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('incomplete', 'Incomplete'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resubmitted', 'Resubmitted by User'), ('rollback', 'Rollback Requested')], default='pending', max_length=20),
        ),
    ]
