# Generated by Django 6.0.5 on 2026-09-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_alter_bookingcustomers_verification_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingcustomers',
            old_name='passport_photo',
            new_name='digital_photo',
        ),
        migrations.AddField(
            model_name='bookingcustomers',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingcustomers',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bookingcustomers',
            name='passport_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
