# Generated by Django 6.0.5 on 2026-06-17 11:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('welcome', 'Welcome'), ('register', 'User Registration'), ('login', 'User Login'), ('logout', 'User Logout'), ('password_reset', 'Password Reset'), ('email_verify', 'Email Verification'), ('profile_update', 'Profile Updated'), ('account_locked', 'Account Locked'), ('account_unlocked', 'Account Unlocked'), ('kyc_submitted', 'KYC Submitted'), ('kyc_pending', 'KYC Pending'), ('kyc_approved', 'KYC Approved'), ('kyc_rejected', 'KYC Rejected'), ('missing_documents', 'Missing Documents'), ('document_uploaded', 'Document Uploaded'), ('document_expired', 'Document Expired'), ('package_created', 'Package Created'), ('package_updated', 'Package Updated'), ('package_deleted', 'Package Deleted'), ('package_approved', 'Package Approved'), ('package_rejected', 'Package Rejected'), ('package_expired', 'Package Expired'), ('package_available', 'Package Available'), ('package_full', 'Package Fully Booked'), ('booking_created', 'Booking Created'), ('booking_pending', 'Booking Pending'), ('booking_confirmed', 'Booking Confirmed'), ('booking_cancelled', 'Booking Cancelled'), ('booking_rejected', 'Booking Rejected'), ('booking_completed', 'Booking Completed'), ('booking_refunded', 'Booking Refunded'), ('traveler_added', 'Traveler Added'), ('traveler_updated', 'Traveler Updated'), ('passport_expiring', 'Passport Expiring'), ('visa_required', 'Visa Required'), ('payment_pending', 'Payment Pending'), ('payment_received', 'Payment Received'), ('payment_verified', 'Payment Verified'), ('payment_failed', 'Payment Failed'), ('payment_refunded', 'Payment Refunded'), ('installment_due', 'Installment Due'), ('invoice_generated', 'Invoice Generated'), ('visa_submitted', 'Visa Submitted'), ('visa_processing', 'Visa Processing'), ('visa_approved', 'Visa Approved'), ('visa_rejected', 'Visa Rejected'), ('flight_added', 'Flight Added'), ('flight_updated', 'Flight Updated'), ('flight_cancelled', 'Flight Cancelled'), ('flight_rescheduled', 'Flight Rescheduled'), ('ticket_issued', 'Ticket Issued'), ('hotel_confirmed', 'Hotel Confirmed'), ('hotel_changed', 'Hotel Changed'), ('hotel_cancelled', 'Hotel Cancelled'), ('transport_confirmed', 'Transport Confirmed'), ('transport_cancelled', 'Transport Cancelled'), ('ziyarat_schedule', 'Ziyarat Schedule'), ('agent_registered', 'Agent Registered'), ('agent_approved', 'Agent Approved'), ('agent_rejected', 'Agent Rejected'), ('commission_added', 'Commission Added'), ('commission_paid', 'Commission Paid'), ('support_ticket_created', 'Support Ticket Created'), ('support_reply', 'Support Reply'), ('support_closed', 'Support Closed'), ('departure_reminder', 'Departure Reminder'), ('return_reminder', 'Return Reminder'), ('payment_reminder', 'Payment Reminder'), ('document_reminder', 'Document Reminder'), ('offer', 'Special Offer'), ('discount', 'Discount'), ('new_package', 'New Package'), ('announcement', 'Announcement'), ('admin_message', 'Admin Message'), ('maintenance', 'System Maintenance'), ('security_alert', 'Security Alert'), ('system', 'System Notification')], default='system', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('is_seen', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('redirect_url', models.URLField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, help_text='FontAwesome icon class', max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='notifications/images/')),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
